// The nineteen volumes on the shelf: ten works of classical literature and nine
// books of the Bible. Descriptions are plain and factual. Cloth colours stay
// muted so the foil stamping is the only thing that catches the light.

// motif values map to the generators in assets/procedural.js.
// format values map to FORMATS in config.js.

export const CATALOG = [
  {
    id: 'genesis',
    title: 'Genesis',
    attribution: 'The Pentateuch',
    collection: 'scripture',
    era: 'Hebrew Bible',
    format: 'folio',
    cloth: '#5c4a3a',
    headband: '#c9b48c',
    motif: 'arch',
    clothName: 'Bark',
    note: 'The opening book of the Hebrew Bible, from the creation accounts through the patriarchs to Joseph in Egypt.',
  },
  {
    id: 'iliad',
    title: 'The Iliad',
    attribution: 'Homer',
    collection: 'classical',
    era: 'Eighth century BC',
    format: 'quarto',
    cloth: '#6e5b42',
    headband: '#d8c9a4',
    motif: 'meander',
    clothName: 'Tobacco',
    note: 'An epic of the Trojan War, turning on the anger of Achilles and its cost to both armies.',
  },
  {
    id: 'psalms',
    title: 'Psalms',
    attribution: 'Wisdom Literature',
    collection: 'scripture',
    era: 'Hebrew Bible',
    format: 'octavo',
    cloth: '#3f4a52',
    headband: '#bcc6cc',
    motif: 'rule-stack',
    clothName: 'Slate',
    note: 'One hundred and fifty poems of lament, thanksgiving and praise, long used as a book of prayer.',
  },
  {
    id: 'odyssey',
    title: 'The Odyssey',
    attribution: 'Homer',
    collection: 'classical',
    era: 'Eighth century BC',
    format: 'quarto',
    cloth: '#4a5a54',
    headband: '#cbd6cd',
    motif: 'wave',
    clothName: 'Verdigris',
    note: 'The ten year return of Odysseus from Troy to Ithaca, and the household waiting for him.',
  },
  {
    id: 'job',
    title: 'Job',
    attribution: 'Wisdom Literature',
    collection: 'scripture',
    era: 'Hebrew Bible',
    format: 'octavo',
    cloth: '#4a3230',
    headband: '#c4a99a',
    motif: 'rosette',
    clothName: 'Oxblood',
    note: 'A dialogue on undeserved suffering, framed by a wager and answered from the whirlwind.',
  },
  {
    id: 'republic',
    title: 'The Republic',
    attribution: 'Plato',
    collection: 'classical',
    era: 'Fourth century BC',
    format: 'octavo',
    cloth: '#5a5f4a',
    headband: '#cdd0bb',
    motif: 'column',
    clothName: 'Olive',
    note: 'A dialogue on justice that builds an imagined city in order to examine the soul.',
  },
  {
    id: 'proverbs',
    title: 'Proverbs',
    attribution: 'Wisdom Literature',
    collection: 'scripture',
    era: 'Hebrew Bible',
    format: 'pocket',
    cloth: '#4e4030',
    headband: '#cbb794',
    motif: 'grid',
    clothName: 'Umber',
    note: 'Short sayings on prudence, speech and work, gathered around the figure of wisdom.',
  },
  {
    id: 'aeneid',
    title: 'The Aeneid',
    attribution: 'Virgil',
    collection: 'classical',
    era: 'First century BC',
    format: 'quarto',
    cloth: '#6a4b3c',
    headband: '#d9bfa2',
    motif: 'laurel',
    clothName: 'Sienna',
    note: 'The flight of Aeneas from burning Troy and the founding of the line that became Rome.',
  },
  {
    id: 'ecclesiastes',
    title: 'Ecclesiastes',
    attribution: 'Wisdom Literature',
    collection: 'scripture',
    era: 'Hebrew Bible',
    format: 'pocket',
    cloth: '#3d4038',
    headband: '#b8bdad',
    motif: 'rule-stack',
    clothName: 'Basalt',
    note: 'A study of what lasts, written by a teacher who has tried everything and found most of it passing.',
  },
  {
    id: 'meditations',
    title: 'Meditations',
    attribution: 'Marcus Aurelius',
    collection: 'classical',
    era: 'Second century',
    format: 'pocket',
    cloth: '#4c4f57',
    headband: '#c3c7cf',
    motif: 'starfield',
    clothName: 'Storm',
    note: 'Private notes written on campaign by a Roman emperor practising Stoic discipline.',
  },
  {
    id: 'isaiah',
    title: 'Isaiah',
    attribution: 'The Major Prophets',
    collection: 'scripture',
    era: 'Hebrew Bible',
    format: 'quarto',
    cloth: '#453a4a',
    headband: '#c0b4c6',
    motif: 'keystone',
    clothName: 'Damson',
    note: 'Prophecy of judgement and return, including the passages on the servant and the comfort of exiles.',
  },
  {
    id: 'histories',
    title: 'The Histories',
    attribution: 'Herodotus',
    collection: 'classical',
    era: 'Fifth century BC',
    format: 'folio',
    cloth: '#7a6244',
    headband: '#e0cda6',
    motif: 'meander',
    clothName: 'Ochre',
    note: 'An enquiry into the Persian wars that collects the customs and stories of the known world.',
  },
  {
    id: 'john',
    title: 'The Gospel of John',
    attribution: 'The Gospels',
    collection: 'scripture',
    era: 'New Testament',
    format: 'octavo',
    cloth: '#2f3f42',
    headband: '#b0c1c3',
    motif: 'rosette',
    clothName: 'Deep teal',
    note: 'The fourth gospel, opening with the word and structured around seven signs.',
  },
  {
    id: 'metamorphoses',
    title: 'Metamorphoses',
    attribution: 'Ovid',
    collection: 'classical',
    era: 'First century',
    format: 'quarto',
    cloth: '#6b4f52',
    headband: '#d9bcbd',
    motif: 'wave',
    clothName: 'Rosewood',
    note: 'A continuous poem of transformations running from the creation of the world to the age of Caesar.',
  },
  {
    id: 'romans',
    title: 'Romans',
    attribution: 'The Pauline Epistles',
    collection: 'scripture',
    era: 'New Testament',
    format: 'pocket',
    cloth: '#4a2f2f',
    headband: '#c5a396',
    motif: 'column',
    clothName: 'Claret',
    note: 'A letter to a church Paul had not yet visited, setting out his fullest argument on faith and law.',
  },
  {
    id: 'confessions',
    title: 'Confessions',
    attribution: 'Augustine',
    collection: 'classical',
    era: 'Fourth century',
    format: 'octavo',
    cloth: '#57453c',
    headband: '#d0bba9',
    motif: 'arch',
    clothName: 'Chestnut',
    note: 'An account of a long conversion, written as an address to God and often called the first autobiography.',
  },
  {
    id: 'ethics',
    title: 'Nicomachean Ethics',
    attribution: 'Aristotle',
    collection: 'classical',
    era: 'Fourth century BC',
    format: 'octavo',
    cloth: '#5f5844',
    headband: '#d3ceb4',
    motif: 'grid',
    clothName: 'Khaki',
    note: 'Ten books on character, habit and the good life, built around the idea of virtue as a mean.',
  },
  {
    id: 'revelation',
    title: 'Revelation',
    attribution: 'Apocalyptic',
    collection: 'scripture',
    era: 'New Testament',
    format: 'octavo',
    cloth: '#523036',
    headband: '#cba39f',
    motif: 'starfield',
    clothName: 'Port',
    note: 'A vision recorded on Patmos, written in symbols to churches under pressure.',
  },
  {
    id: 'divine-comedy',
    title: 'The Divine Comedy',
    attribution: 'Dante Alighieri',
    collection: 'classical',
    era: 'Fourteenth century',
    format: 'folio',
    cloth: '#63414a',
    headband: '#d7b6b3',
    motif: 'keystone',
    clothName: 'Mulberry',
    note: 'A journey through hell, purgatory and paradise, written in Italian across one hundred cantos.',
  },
];

export const COLLECTIONS = {
  classical: 'Classical literature',
  scripture: 'Books of the Bible',
};

export function findIndexById(id) {
  return CATALOG.findIndex((volume) => volume.id === id);
}
